project:
  type: website

website:
  title: "B(E)3M35HYS – Hybrid systems"
  page-footer: "Copyright 2024, Zdeněk Hurák"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "0. Introduction"
        contents:
          - intro.qmd
          - intro_outline.qmd
          - intro_references.qmd
      - section: "1. Discrete-event systems: Automata"
        contents:
          - des.qmd
          - des_automata.qmd  
          - des_software.qmd
          - des_references.qmd
      - section: "2. Discrete-event systems: Petri nets"  
        contents:  
          - petri_nets.qmd  
          - petri_nets_timed.qmd 
          - petri_nets_software.qmd 
          - petri_nets_references.qmd
      - section: "3. Discrete-event systems: Max-plus systems"  
        contents:
          - max_plus_algebra.qmd
          - max_plus_systems.qmd  
          - max_plus_software.qmd
          - max_plus_references.qmd
      - section: "4. Hybrid systems: Hybrid automata"
        contents:
          - hybrid_automata.qmd
          - hybrid_automata_software.qmd
          - hybrid_automata_references.qmd
      - section: "5. Hybrid systems: Hybrid equations"
        contents:
          - hybrid_equations.qmd
          - hybrid_equations_software.qmd
          - hybrid_equations_references.qmd
      - section: "6. Some classes of hybrid systems"
        contents:
          - classes_reset.qmd
          - classes_switched.qmd
          - classes_PWA.qmd
          - classes_software.qmd
          - classes_references.qmd
      - section: "7. Solution"
        contents:
          - solution_concepts.qmd
          - solution_types.qmd
          - solution_references.qmd
      - section: "8. Stability"
        contents:
          - stability_recap.qmd
          - stability_concepts.qmd
          - stability_via_common_lyapunov_function.qmd
          - stability_via_multiple_lyapunov_function.qmd
          - stability_software.qmd
          - stability_references.qmd
      - section: "9. Complementarity systems"
        contents:
          - complementarity_constraints.qmd
          - complementarity_systems.qmd
          - complementarity_simulations.qmd
          - complementarity_software.qmd
          - complementarity_references.qmd
      - section: "10. Mixed logical dynamical (MLD) systems"
        contents:
          - mld_DHA.qmd
          - mld_logic_vs_inequalities.qmd
          - mld_mld_and_pwa.qmd
          - mld_software.qmd
          - mld_references.qmd
      - section: "11. Model predictive control (MPC) for MLD systems"
        contents:
          - mpc_mld_online.qmd
          - mpc_mld_explicit.qmd
          - mpc_mld_software.qmd
          - mpc_mld_references.qmd
      - section: "12. Formal verification"
        contents:
          - verification_intro.qmd
          - verification_reachability.qmd
          - verification_barrier.qmd
          - verification_temporal_logics.qmd
          - verification_software.qmd
          - verification_references.qmd
  repo-url: https://github.com/hurak/hys
  repo-actions: [issue]       
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true