---
title: "Software"
bibliography: 
    - ref_PWA.bib
#csl: ieee-control-systems.csl
format:
    html:
        html-math-method: katex
        code-fold: true
        code-summary: "Show the code"
crossref:
  fig-prefix: Fig 
#engine: julia
---

Reset systems, switched systems, and piecewise affine (PWA) systems can all be viewed as special classes of hybrid systems, and as such can be modelled and simulated using software for hybrid systems (or even general purpose modelling and simulation software).

However, there are also some dedicated software tools/packages/libraries for PWA systems:

- [PLECS](https://www.plexim.com/products/plecs)
    - Power electronics
    - Commercial
- [Multiparametric Toolbox (MPT) for Matlab](https://www.mpt3.org)
    - General
    - Special data type/class (and some related functions) for PWA systems is available in the section on [Modeling of dynamical systems in MPT3](https://www.mpt3.org/UI/Systems).
    - Free and open source.

Although some more free and open-source software packages for PWA systems can be found on the internet, none of them (at as far as we know) is actively developed or at least maintained anymore:   

- [PWATOOLS](https://github.com/bsamadi/PWATOOLS) toolbox for Matlab, which accompanies the recently published book @rodriguesPiecewiseAffineControl2019. Unfortunately, this ten-year old toolbox is no longer working with the recent releases of Matlab and the author is no longer maintaining it.
- [PWLTool](https://portal.research.lu.se/en/publications/pwltool-a-matlab-toolbox-for-piecewise-linear-system) toolbox for Matlab: some traces of this toolbox can be found on the internet, but this one seems even older, obviously back then accompanying the book @johanssonPiecewiseLinearControl2003.

Overall, besides the MPT toolbox that is still being actively developed (by our colleagues at STU Bratislava), not much is currently available within the open-source software domain... :-(

