---
title: "References"
bibliography: ref_hybrid.bib
format:
    html     
---

The discipline of *hybrid system* is huge and spans several areas of science and engineering. As a result, finding a *single* comprehensive reference is difficult if not impossible. The more so that our selection of topics is inevitably biased. Therefore, we will always provide a list of references when studying particular topics. Admittedly, our selections of both topics and references will mostly be biased towards control engineering.

## Overview texts freely available online
Among the texts that provide motivation for studying hybrid systems as well as some introduction into theoretical and computational frameworks, we recommend @heemelsIntroductionHybridSystems2009, which is also [available on the author's webpage](https://heemels.tue.nl/content/papers/HeeLeh_BOOK_CONTRIB09a.pdf). Yet another overview, which is also available online, is @johanssonHybridControlSystems2004. And yet another is @deschutterSurveyModelingAnalysis2009, which is [available on the author's web page](https://pub.deschutter.info/abs/09_007.html). The quartet of recommended online resources is concluded by @lygerosLectureNotesHybrid2004.

## Text available in print
Among the printed books, for which we are not aware of legally available online version, the slim book @vanderschaftIntroductionHybridDynamical2000 can be regarded as the classic. The handbook @lunzeHandbookHybridSystems2009 contains a wealth of contributions from several authors (in fact two of the online resources linked above are chapters from this book). The latest textbook on the topic of hybrid systems is @linHybridDynamicalSystems2022.

@sanfeliceHybridFeedbackControl2021

@goebelHybridDynamicalSystems2012

@goebelHybridDynamicalSystems2009

@borrelliPredictiveControlLinear2017

