---
title: "Software"
bibliography: 
    - ref_hybrid.bib
    - ref_verification.bib
    - ref_temporal.bib
csl: ieee-control-systems.csl
format: html
---

## Reachability analysis

### Reachability analysis based on set propagation

#### In Matlab

- Multiparametric Toolbox (MPT): [https://www.mpt3.org](https://www.mpt3.org)
  - Some functionality (invariant set computation) purely for discrete-time systems
- CORA: [https://tumcps.github.io/CORA/](https://tumcps.github.io/CORA/)
  - Supports also continuous-time systems, and not only linear but also nonlinear and hybrid ones.

Quite a few other tools can be found on the web but mostly unmaintained.

#### In Julia

- ReachabilityAnalysis.jl: [https://juliareach.github.io/ReachabilityAnalysis.jl/](https://juliareach.github.io/ReachabilityAnalysis.jl/dev/)

#### In Python

- Sorry, I am not aware of anything, but I will gladly add whatever you suggest. Just keep in mind that the tool should be actively maintained to be useful at least for study purposes.

### Barrier certificates

No specialized software. At the moment just the same computational tools as for Lyapunov stability analysis – nonnegative (sum-of-squares) polynomial optimization, etc.

### Temporal logics

Mainly some experimental code accompanying research papers.

#### In Julia

- [SignalTemporalLogic.jl](https://github.com/sisl/SignalTemporalLogic.jl)

#### In Python

#### In Matlab

- [Breach](https://github.com/decyphir/breach) toolbox for Matlab

- Beware that Matlab's toolboxes such as [Requirements Toolbox](https://www.mathworks.com/products/requirements-toolbox.html) and [Simulink Design Verifier](https://www.mathworks.com/products/simulink-design-verifier.html) mention some temporal logic and temporal operators, but they do not adhere to the syntax of STL.
