project:
  type: website

csl: ieee-control-systems.csl

website:
  title: "B(E)3M35HYS – Hybrid systems"
  page-footer: "Copyright 2025, Zdeněk Hurák"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "0. Introduction"
        contents:
          - 0_intro/intro.qmd
          - 0_intro/outline.qmd
          - 0_intro/rules.qmd
          - 0_intro/similar.qmd
          - 0_intro/references.qmd
      - section: "1. Discrete-event systems: Automata"
        contents:
          - 1_des/goals.qmd
          - 1_des/des.qmd
          - 1_des/automata.qmd  
          - 1_des/software.qmd
          - 1_des/references.qmd
      - section: "2. Discrete-event systems: Petri nets"  
        contents:
          - 2_petri_nets/goals.qmd  
          - 2_petri_nets/petri_nets.qmd  
          - 2_petri_nets/petri_nets_timed.qmd 
          - 2_petri_nets/software.qmd 
          - 2_petri_nets/references.qmd
      - section: "3. Discrete-event systems: Max-plus systems"  
        contents:
          - 3_max_plus/goals.qmd
          - 3_max_plus/max_plus_algebra.qmd
          - 3_max_plus/max_plus_systems.qmd  
          - 3_max_plus/software.qmd
          - 3_max_plus/references.qmd
      - section: "4. Hybrid systems: Hybrid automata"
        contents:
          - 4_hybrid_automata/goals.qmd
          - 4_hybrid_automata/hybrid_automata.qmd
          - 4_hybrid_automata/software.qmd
          - 4_hybrid_automata/references.qmd
      - section: "5. Hybrid systems: Hybrid equations"
        contents:
          - 5_hybrid_equations/goals.qmd
          - 5_hybrid_equations/hybrid_equations.qmd
          - 5_hybrid_equations/software.qmd
          - 5_hybrid_equations/references.qmd
      - section: "6. Some classes of hybrid systems"
        contents:
          - 6_classes/goals.qmd
          - 6_classes/reset.qmd
          - 6_classes/switched.qmd
          - 6_classes/PWA.qmd
          - 6_classes/software.qmd
          - 6_classes/references.qmd
      - section: "7. Solution"
        contents:
          - 7_solution/goals.qmd
          - 7_solution/concepts.qmd
          - 7_solution/types.qmd
          - 7_solution/references.qmd
      - section: "8. Stability I."
        contents:
          - 8_stability_1/goals.qmd
          - 8_stability_1/recap.qmd
          - 8_stability_1/concepts.qmd
          - 8_stability_1/common_lyapunov_function.qmd
          - 8_stability_1/software.qmd
          - 8_stability_1/references.qmd
      - section: "9. Stability II."
        contents:
          - 9_stability_2/goals.qmd
          - 9_stability_2/multiple_lyapunov_function.qmd
          - 9_stability_2/software.qmd
          - 9_stability_2/references.qmd    
      - section: "10. Complementarity systems"
        contents:
          - 10_complementarity/goals.qmd
          - 10_complementarity/constraints.qmd
          - 10_complementarity/systems.qmd
          - 10_complementarity/simulations.qmd
          - 10_complementarity/software.qmd
          - 10_complementarity/references.qmd
      - section: "11. Mixed logical dynamical (MLD) systems"
        contents:
          - 11_mld/goals.qmd
          - 11_mld/DHA.qmd
          - 11_mld/logic_vs_inequalities.qmd
          - 11_mld/DHA_parts_as_inequalities.qmd
          - 11_mld/mld_and_pwa.qmd
          - 11_mld/software.qmd
          - 11_mld/references.qmd
      - section: "12. Model predictive control (MPC) for MLD systems"
        contents:
          - 12_mpc/goals.qmd
          - 12_mpc/online.qmd
          - 12_mpc/explicit.qmd
          - 12_mpc/software.qmd
          - 12_mpc/references.qmd
      - section: "13. Formal verification I."
        contents:
          - 13_verification_1/goals.qmd
          - 13_verification_1/intro.qmd
          - 13_verification_1/reachability.qmd
          - 13_verification_1/barrier.qmd
          - 13_verification_1/software.qmd
          - 13_verification_1/references.qmd
      - section: "14. Formal verification II."
        contents:
          - 14_verification_2/goals.qmd
          - 14_verification_2/temporal_logics.qmd
          - 14_verification_2/software.qmd
          - 14_verification_2/references.qmd    
  repo-url: https://github.com/hurak/hys
  repo-actions: [issue]       
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true