---
title: "Rules of the course"
format: html
---

## Grading
The only grading occasion is the final exam. Every students will choose some three topics covered in the course and the exam will then consist of discussing these topics in some depth.


## Optional semestral project
A student can (optionally) come up with a small project of their choice. Successfully accomplished project will improve the final grade at the exam. Typically such project can derive from a diploma project. It can be just an application of particular technique presented in the course. But it can also be a (computational) demonstration of some other (yet related) technique that the students studies in research literature. Shaping the assignment/scope of the project will be done with the teacher. 

The project can be rather small, this is not another diploma thesis. As a concrete outcome, either a few page report, or a few presentation slides or even some well-commented code can be delivered. Every nice work counts.