---
title: "Similar courses"
format: html
---

You may find it useful at least to be aware of these courses if not even to explore them at some detail. But we do not particularly try to align our course with any of these as the backgrounds of the students and the teachers vary.

## At other universities
- Ricardo G. Sanfelice: Hybrid Control Design, PhD Course at the University of Bologna, 2018, [https://hybrid.soe.ucsc.edu/hcd18](https://hybrid.soe.ucsc.edu/hcd18).
- Maria Prandini: Hybrid Systems, PhD course at Lund University, 2015, [https://www.control.lth.se/education/doctorate-program/hybrid-systems/](https://www.control.lth.se/education/doctorate-program/hybrid-systems/).
- Wei Zhang: ECE 7850 Hybrid Systems: Theory and Applications, The Ohio State University, Spring 2017, [http://www2.ece.ohio-state.edu/~zhang/HybridSystemsClass/index.html](http://www2.ece.ohio-state.edu/~zhang/HybridSystemsClass/index.html).
- Dimos Dimarogonas: EL2450 Hybrid and Embedded Control Systems, KTH, 2021, [https://www.kth.se/student/kurser/kurs/EL2450?l=en](https://www.kth.se/student/kurser/kurs/EL2450?l=en) (requires login).
- De Persis: WMIE014-05 Advanced Digital and Hybrid Control Systems, Groningen, 2021/22, [https://www.rug.nl/ocasys/rug/vak/show?code=WMIE014-05](https://www.rug.nl/ocasys/rug/vak/show?code=WMIE014-05).
- Bart de Schutter: Modeling and Control of Hybrid Systems (SC42075), MSc course, TU Delft, 2021, [https://www.dcsc.tudelft.nl/~bdeschutter/hs/index.html](https://www.dcsc.tudelft.nl/~bdeschutter/hs/index.html).
- Claire Tomlin: EE C291E/ME C290S Hybrid Systems---Computation and Control, UC Berkeley, Spring 2021, [https://inst.eecs.berkeley.edu/~ee291e/sp21/](https://inst.eecs.berkeley.edu/~ee291e/sp21/).
- João P. Hespanha: ECE229 Hybrid and Switched Systems, UCSB, Fall 2005, [https://web.ece.ucsb.edu/~hespanha/ece229/](https://web.ece.ucsb.edu/~hespanha/ece229/).
- Imura Jun-Ichi: Hybrid Systems Control, Tokyo Institute of Technology, 2018, [http://www.ocw.titech.ac.jp/index.php?module=General&action=T0300&JWC=201804589&lang=EN](http://www.ocw.titech.ac.jp/index.php?module=General&action=T0300&JWC=201804589&lang=EN).
- Inseok Hwang and Jianghai Hu: AAE 66800 Hybrid Systems: Theory and Applications, Purdue University, 2014, [https://engineering.purdue.edu/AAE/academics/course-descriptions/AAE690_Hybrid_System_Theory_Applications](https://engineering.purdue.edu/AAE/academics/course-descriptions/AAE690_Hybrid_System_Theory_Applications).
- O. Stursberg and L. Malkolf: FB16 - 4455 Hy­brid and Net­wor­ked Con­trol Sys­tems (HNCS), [https://www.uni-kassel.de/eecs/control/lehre/hybrid-and-networked-control-systems](https://www.uni-kassel.de/eecs/control/lehre/hybrid-and-networked-control-systems).
- Necmiye Ozay: EECS 598-002 Hybrid Systems: Specification, Verification and Control, University of Michigan, Fall 2015, [http://web.eecs.umich.edu/~necmiye/hybridsystemsF15.html](http://web.eecs.umich.edu/~necmiye/hybridsystemsF15.html).

## At CTU Prague
- Pavel Burget: BE3M35SDU Discrete Event Systems (within [https://moodle.fel.cvut.cz/](https://moodle.fel.cvut.cz/)). Last time run in 2020.
