---
title: "Literature"
bibliography: ../references/ref_hybrid.bib
format:
    html     
---

The literature for hybrid systems is vast. I found choosing  a single resource as the reference for our course a daunting task. 

Chapter 2 of the recently published book @linHybridDynamicalSystems2022 provides an up to date introduction to hybrid systems. But I am not happy about their lack of consistency in defining the roles of guards and (location/mode) invariants as the conditions for transitions. Furthermore, it is currently not available online (neither through our institutional subscription nor for free on the authors' webpage). Among the popular references is a a thin book @vanderschaftIntroductionHybridDynamical2000, but it is not freely available online either. Therefore, I am giving here a list of a few more recommendable references by leaders in the field.

The often cited lecture notes @lygerosLectureNotesHybrid2004. An updated version @lygerosHybridSystemsFoundations2020 was available online for a while, but recently the link seems to be broken (perhaps the authors have been turning them into a book). The book chapter @heemelsIntroductionHybridSystems2009 is a good and much shorter overview. It is freely available online on the authors web page. A similar overview role is played by the encyclopedia article @johanssonHybridControlSystems2004, which is also freely available online.

