---
title: "Course outline"
format: html
---

The course is structured into 13 topics, each of them corresponding to one lecture. The topics are as follows:

- Discrete-event systems 
    1. (State) automata (state machines) (incl. timed variants)
    2. Petri nets (and timed Petri nets), 
    3. Max-Plus algebra and Max-Plus Linear (MPL) systems
- Hybrid systems 
    4. Hybrid automata
    5. Hybrid equations
- Special classes of hybrid systems
    6. Reset (control) systems, Switched/switching systems, Piecewise affine systems (PWA) 
    7. Complementarity dynamical systems (and complementarity optimization constraints)    
8. Solutions of hybrid systems
- Stability of hybrid systems
    9. Common Lyapunov function 
        - Quadratic Lyapunov function via linear matrix inequality (LMI) and semidefinite programming (SDP) 
        - Polynomial Lyapunov function via sum-of-squares (SOS) programming
    10. Piecewise quadratic/polynomial Lyapunov function via S-procedure
11. Mixed-logical dynamical (MLD) description of hybrid systems
12. Model predictive control (MPC) for MLD systems 
13. (Formal) verification of hybrid systems